language: android
jdk: oraclejdk8
env:
  global:
  - GRADLE_OPTS="-Xmx512m"
  matrix:
  - ADB_INSTALL_TIMEOUT=15 ANDROID_BUILD_TOOLS_VERSION=24.0.2 ANDROID_TARGET=android-24
    ANDROID_ABI=armeabi-v7a
cache:
  directories:
  - "${TRAVIS_BUILD_DIR}/android/gradle/caches/"
  - "${TRAVIS_BUILD_DIR}/android/gradle/wrapper/dists/"
  - "$HOME/android/.gradle/caches/"
  - "$HOME/android/.gradle/wrapper/"
android:
  components:
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - "$ANDROID_TARGET"
  - android-24
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-$ANDROID_TARGET
# before_script:
#   - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
#   - emulator -avd test -no-skin -no-audio -no-window &
#   - android-wait-for-emulator
#   - adb shell input keyevent 82 &

script:
  - ./gradlew build
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck
  - ./gradlew assembleRelease

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4d7532d96e0012e71442
    on_success: always
    on_failure: always
    on_start: false

after_success:
  - chmod +x exec/apk-gen.sh
  - sh exec/apk-gen.sh
